version: "3.8"
services:

    # PHP service
    app:
        build: .
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
